In [10]:
#Project on loan apporval
import pandas as pd
import numpy as np
data=pd.read_csv("LoanApprovalPrediction.csv")

In [11]:
data.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [12]:
data.tail()

Loan_ID  Gender Married  Dependents Education Self_Employed  \
593  LP002978  Female      No         0.0  Graduate            No   
594  LP002979    Male     Yes         3.0  Graduate            No   
595  LP002983    Male     Yes         1.0  Graduate            No   
596  LP002984    Male     Yes         2.0  Graduate            No   
597  LP002990  Female      No         0.0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
593             2900                0.0        71.0             360.0   
594             4106                0.0        40.0             180.0   
595             8072              240.0       253.0             360.0   
596             7583                0.0       187.0             360.0   
597             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
593             1.0         Rural           Y  
594             1.0         Rural           Y  
595             1.0         Urban           Y  
596             1.0         Urban           Y  
597             0.0     Semiurban           N

In [13]:
data.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            598 non-null    object 
 1   Gender             598 non-null    object 
 2   Married            598 non-null    object 
 3   Dependents         586 non-null    float64
 4   Education          598 non-null    object 
 5   Self_Employed      598 non-null    object 
 6   ApplicantIncome    598 non-null    int64  
 7   CoapplicantIncome  598 non-null    float64
 8   LoanAmount         577 non-null    float64
 9   Loan_Amount_Term   584 non-null    float64
 10  Credit_History     549 non-null    float64
 11  Property_Area      598 non-null    object 
 12  Loan_Status        598 non-null    object 
dtypes: float64(5), int64(1), object(7)
memory usage: 60.9+ KB


In [15]:
#As part of data preprocessing we can remove:
#loan id column
#convert the categorical value to numeric
#replace null values with the correspoding mean of the column

In [16]:
data.drop(["Loan_ID"],axis=1)

Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No         0.0      Graduate            No             5849   
1      Male     Yes         1.0      Graduate            No             4583   
2      Male     Yes         0.0      Graduate           Yes             3000   
3      Male     Yes         0.0  Not Graduate            No             2583   
4      Male      No         0.0      Graduate            No             6000   
..      ...     ...         ...           ...           ...              ...   
593  Female      No         0.0      Graduate            No             2900   
594    Male     Yes         3.0      Graduate            No             4106   
595    Male     Yes         1.0      Graduate            No             8072   
596    Male     Yes         2.0      Graduate            No             7583   
597  Female      No         0.0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
593                0.0        71.0             360.0             1.0   
594                0.0        40.0             180.0             1.0   
595              240.0       253.0             360.0             1.0   
596                0.0       187.0             360.0             1.0   
597                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
593         Rural           Y  
594         Rural           Y  
595         Urban           Y  
596         Urban           Y  
597     Semiurban           N  

[598 rows x 12 columns]

In [57]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [86]:
data['Gender'].unique()

array([1, 0])

In [93]:
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [20]:
data['Gender'].unique()

array([1, 0])

In [21]:
data['Married']=label_encoder.fit_transform(data['Married'])

In [22]:
data['Married'].unique()

array([0, 1])

In [23]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [24]:
data['Education']=label_encoder.fit_transform(data['Education'])

In [25]:
data['Education'].unique()

array([0, 1])

In [26]:
data.head()

Loan_ID  Gender  Married  Dependents  Education Self_Employed  \
0  LP001002       1        0         0.0          0            No   
1  LP001003       1        1         1.0          0            No   
2  LP001005       1        1         0.0          0           Yes   
3  LP001006       1        1         0.0          1            No   
4  LP001008       1        0         0.0          0            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [27]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [28]:
data['Self_Employed']=label_encoder.fit_transform(data['Self_Employed'])

In [29]:
data['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [30]:
data['Property_Area']=label_encoder.fit_transform(data['Property_Area'])

In [31]:
data['Loan_Status'].unique()

array(['Y', 'N'], dtype=object)

In [32]:
data['Loan_Status']=label_encoder.fit_transform(data['Loan_Status'])

In [33]:
data.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0         0.0          0              0   
1  LP001003       1        1         1.0          0              0   
2  LP001005       1        1         0.0          0              1   
3  LP001006       1        1         0.0          1              0   
4  LP001008       1        0         0.0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [34]:
df=data.drop(['Loan_ID'],axis=1)

In [35]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [95]:
for col in df.columns:
    df[col]=df[col].fillna(df[col].mean())

In [37]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  144.968804             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [38]:
df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [39]:
x=df.drop(['Loan_Status'],axis=1)#independant variables

In [40]:
y=df['Loan_Status']#Dependent variable

In [41]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  144.968804             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [42]:
x.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  144.968804             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.85)

In [44]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [45]:
model.fit(x_train,y_train)

D:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [46]:
y_hat= model.predict(x_test)

In [47]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_hat)

In [48]:
print(acc)

0.7777777777777778
